import type { Config } from "tailwindcss"

const config = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        "primary-fixed-dim": "#00dbe7",
        "on-background": "#d4e4fa",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffba20",
        "on-surface-variant": "#b9cacb",
        "error-container": "#93000a",
        "background": "#051424",
        "on-tertiary-fixed-variant": "#5e4200",
        "on-surface": "#d4e4fa",
        "error": "#ffb4ab",
        "on-tertiary": "#412d00",
        "outline-variant": "#3a494b",
        "surface-tint": "#00dbe7",
        "surface-container-low": "#0d1c2d",
        "surface-bright": "#2c3a4c",
        "inverse-surface": "#d4e4fa",
        "surface-container-lowest": "#010f1f",
        "inverse-primary": "#00696f",
        "tertiary-fixed": "#ffdea8",
        "primary-fixed": "#74f5ff",
        "surface": "#051424",
        "on-primary": "#00363a",
        "secondary-fixed": "#ffdadb",
        "secondary": "#ffb2b8",
        "primary": {
          DEFAULT: "#e1fdff",
          foreground: "#00363a",
        },
        "tertiary-container": "#ffd58c",
        "on-primary-fixed": "#002022",
        "secondary-container": "#ff506e",
        "outline": "#849495",
        "inverse-on-surface": "#233143",
        "secondary-fixed-dim": "#ffb2b8",
        "surface-dim": "#051424",
        "on-secondary-fixed-variant": "#91002d",
        "primary-container": "#00f2ff",
        "on-error": "#690005",
        "on-tertiary-container": "#7e5900",
        "tertiary": "#fff6ed",
        "surface-variant": "#273647",
        "on-secondary-fixed": "#40000f",
        "on-secondary": "#67001d",
        "on-primary-container": "#006a71",
        "on-primary-fixed-variant": "#004f54",
        "on-tertiary-fixed": "#271900",
        "surface-container-highest": "#273647",
        "on-secondary-container": "#5b0018",
        "surface-container-high": "#1c2b3c",
        "surface-container": "#122131",
        
        // Retain shadcn basic overrides using our colors
        border: "#849495",
        input: "#3a494b",
        ring: "#00dbe7",
        foreground: "#d4e4fa",
        card: {
          DEFAULT: "#051424",
          foreground: "#d4e4fa",
        },
        popover: {
          DEFAULT: "#051424",
          foreground: "#d4e4fa",
        },
        muted: {
          DEFAULT: "#273647",
          foreground: "#b9cacb",
        },
        accent: {
          DEFAULT: "#00dbe7",
          foreground: "#00363a",
        },
        destructive: {
          DEFAULT: "#ff506e",
          foreground: "#5b0018",
        },
      },
      borderRadius: {
        lg: "0.25rem",
        md: "0.125rem",
        sm: "0.125rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "panel-padding": "20px",
        "margin-page": "24px",
        "gutter": "16px",
        "unit": "4px",
      },
      fontFamily: {
        "headline-sm": ["Inter"],
        "code-sm": ["JetBrains Mono"],
        "label-caps": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "display-lg": ["Inter"],
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "code-sm": ["12px", { lineHeight: "16px", fontWeight: "450" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config

export default config
